#Q1) Write Python Programs to use various operators in Python

In [2]:
#1. Write Python Programs to use various operators in Python
a = 10
b = 6
print('a + b  =',a+b)

print('a-b =',a-b)

print('a*b =',a*b)

print('a/b =',a/b)

print('a % b =',a%b)

print('a ** b =',a**b)

print('a > b is',a>b)

print('a < b is',a<b)

print('a == b is',a==b)

print('a != b is',a!=b)

print('a >= b is',a>=b)

print('a <= b is',a<=b)

a + b  = 16
a-b = 4
a*b = 60
a/b = 1.6666666666666667
a % b = 4
a ** b = 1000000
a > b is True
a < b is False
a == b is False
a != b is True
a >= b is True
a <= b is False

#Q2) Create list of elements and slice and dice it

In [3]:
list1 = [5,10,15,20,25,30,35]
list1

[5, 10, 15, 20, 25, 30, 35]

In [5]:
list1[2:4]

[15, 20]

In [6]:
list1[:-2]

[5, 10, 15, 20, 25]

In [7]:
list1[:]

[5, 10, 15, 20, 25, 30, 35]

#Q3) Using while loop accept numbers until sum of numbers is less than 100

In [8]:
num = int(input("Enter a number: "))
sum = 0
sum= sum+num
while sum< 100:
    if sum < 100:
        num = int(input("Enter another number: "))
        sum = sum + num
    elif sum>100:
        print('Sum is greater than 100')

Enter a number: 5
Enter another number: 4
Enter another number: 5
Enter another number: 95

#Q4) Write a python program Read & write Excel files

In [9]:
!pip install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.9/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.9/dist-packages (from openpyxl) (1.1.0)

In [15]:
import openpyxl
my_wb = openpyxl.Workbook()
my_sheet = my_wb.active
c1 = my_sheet.cell(row = 1, column = 1)
c1.value = "Mayur"
c2 = my_sheet.cell(row= 1 , column = 2)
c2.value = "Suyash"
c3 = my_sheet['B3']
c3.value = "29"
# B2 = column = 2 & row = 2.
c4 = my_sheet['C3']
c4.value = "31"
my_wb.save("/content/Book1.xlsx")

In [17]:
import pandas as pd
book = pd.read_excel('/content/Book1.xlsx')
book

   Mayur  Suyash  Unnamed: 2
0    NaN     NaN         NaN
1    NaN    29.0        31.0

#Q5) Write a python program to scrape reviews from a commercial web site

In [18]:
!pip install requests

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests) (3.4)

In [19]:
import requests
from bs4 import BeautifulSoup

In [20]:
url = "https://www.amazon.in/Columbia-Mens-wind-\
resistant-Glove/dp/B0772WVHPS/?_encoding=UTF8&pd_rd\
_w=d9RS9&pf_rd_p=3d2ae0df-d986-4d1d-8c95-aa25d2ade606&pf\
_rd_r=7MP3ZDYBBV88PYJ7KEMJ&pd_rd_r=550bec4d-5268-41d5-\
87cb-8af40554a01e&pd_rd_wg=oy8v8&ref_=pd_gw_cr_cartx&th=1"

In [21]:
HEADERS = ({'User-Agent':
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) \
            AppleWebKit/537.36 (KHTML, like Gecko) \
            Chrome/90.0.4430.212 Safari/537.36',
            'Accept-Language': 'en-US, en;q=0.5'})

In [22]:
def getdata(url):
    r = requests.get(url, headers=HEADERS)
    return r.text

def html_code(url):
  
    htmldata = getdata(url)
    soup = BeautifulSoup(htmldata, 'html.parser')
  
    # display html code
    return (soup)
  
soup = html_code(url)

In [23]:
def cus_rev(soup):
	data_str = ""

	for item in soup.find_all("div", class_="a-expander-content \
	reviewText review-text-content a-expander-partial-collapse-content"):
		data_str = data_str + item.get_text()

	result = data_str.split("\n")
	return (result)

In [24]:
rev_result = []
for i in cus_rev(soup):
	if i is "":
		pass
	else:
		rev_result.append(i)
rev_result

<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-24-4862ec7459ab>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if i is "":

[]

#Q6) Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [29]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

#Q7) Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [30]:
l = [17.32, 14.10, 100, 38.24]
print("Original List:",l)
a = np.array(l)
print("One-dimensional NumPy array: ",a)

Original List: [17.32, 14.1, 100, 38.24]
One-dimensional NumPy array:  [ 17.32  14.1  100.    38.24]

#Q8)  Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [31]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]